language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - node_modules

# exclude tags
branches:
  only:
    - master

env:
  global:
    - CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER

before_install:
  - openssl aes-256-cbc -K $encrypted_8360855577e2_key -iv $encrypted_8360855577e2_iv -in '.travis/github_deploy_key.enc' -out github_deploy_key -d

before_script:
  - git diff --exit-code yarn.lock
  - yarn check

after_script:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - >
    $(npm bin)/set-up-ssh --key "$encrypted_8360855577e2_key" \
                             --iv "$encrypted_8360855577e2_iv" \
                             --path-encrypted-key ".travis/github_deploy_key.enc"
  - >
    [ "${TRAVIS_BRANCH}" = "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ] &&
    export GIT_TAG=$(make version) ||
    export GIT_TAG=$(make version)-beta
  - >
    [ "${TRAVIS_BRANCH}" = "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ] &&
    export NPM_TAG=latest ||
    export NPM_TAG=beta
  - echo "GIT_TAG=$GIT_TAG"
  - echo "NPM_TAG=$NPM_TAG"
  - git push --tags git@github.com:$TRAVIS_REPO_SLUG.git
deploy:
  provider: npm
  email: web-platform-bot@meetup.com
  tag: $NPM_TAG
  api_key:
    secure: j0LMwZNnOMAM5wMRvWh/GH2zsxioYxhRtwywUDB1jhWlbW84QHNlA0AKJPNWlDKka+SOLUqoQKs4Ax/awxNlyjPCvolusCf5LDoObn56H+MS5sW4Gt8R7w/X9wGpkS8xrQZ4amyFQejcMuIEUzj61aix1HR0k6g+fB4VJpzWIHgsbbYv1Txb8ncFUJPg2N5Gl4lgSKSCCLvSsqFfnFf0bYA8Ci8RG0gHUK2nscZPfvKCP4Jpp+zVo9fahu1F/wwCwisg6Hq6h+/gXK+36r9aPx7Fz3efmllnGTBOThUkgJPkOZU5hWolEQ2lzzmT0iIlKNYjijpCxKe2MGnQIA9Nyxb9mxwjh1M0bzWJaZteZTKcgv47RDL9toHgTRfp9klV52zWXTdl/f1efVIBKef4167PmCvA44blUZ8pfCdBqrrWl50IcH/vLm3ctIGCpAh7yK6yBSaqT1WxCr3rO/37rkKDc8UzEcj5Xuc782UwqHe7ctn5tpGHbsXJwgpPUneLXlrEQyTQ15B6yCqWBhbLrdyquYb1AHPqMlgxANYY+54VpMICkldP1wQv5rS7+cwzQv+/7/NeNaDwj3SVy/f374LxBmGMIbuIXaAvRtnvtKmcvCf+tUuBfoUQTmHEryTz2VWp4nkeQNpi0uZ/9Ip8/U7CPKh2dxZuh6JmcJxGHYA=
  on:
    tags: true
    repo: meetup/mwp-cli
