language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - node_modules

# exclude tags
branches:
  only:
    - master

env:
  global:
    - CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER

before_install:
  - openssl aes-256-cbc -K $encrypted_8360855577e2_key -iv $encrypted_8360855577e2_iv -in '.travis/github_deploy_key.enc' -out github_deploy_key -d
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

before_script:
  - git diff --exit-code yarn.lock
  - yarn check

after_script:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - >
    $(npm bin)/set-up-ssh --key "$encrypted_8360855577e2_key" \
                             --iv "$encrypted_8360855577e2_iv" \
                             --path-encrypted-key ".travis/github_deploy_key.enc"
  - >
    [ "${TRAVIS_BRANCH}" = "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ] &&
    export GIT_TAG=$(make version) ||
    export GIT_TAG=$(make version)-beta
  - >
    [ "${TRAVIS_BRANCH}" = "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ] &&
    export NPM_TAG=latest ||
    export NPM_TAG=beta
  - echo "GIT_TAG=$GIT_TAG"
  - echo "NPM_TAG=$NPM_TAG"
  - npm version $GIT_TAG -m "Version $GIT_TAG built by Travis CI - https://travis-ci.com/$TRAVIS_REPO_SLUG/builds/$TRAVIS_JOB_ID"
  # - git push --tags git@github.com:$TRAVIS_REPO_SLUG.git
  - npm publish --tag $NPM_TAG

after_success:
  - yarn run coveralls
