version: 1

# update_schedule: live is only supported on javascript, ruby:bundler, python, php:composer, dotnet:nuget, rust:cargo, elixir:hex

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    allowed_updates:
    - match:
        update_type: "security"
